
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hypr.land/Configuring/Window-Rules/

#? ------- WINDOWRULES_HYPRLAND_V_0_53 COMPATIBLE ----------------
#   This Config is compatible with windowrules changes in Hyprland v0.53+
#   Any future breaking changes disables this block and notifies the user to update.
#   User template files will be provided in $XDG_DATA_HOME/hyde/templates/hypr/windowrules.conf for manual update.

# hyprlang if WINDOWRULES_HYPRLAND_V_0_53

#      ___    _ _      
#     |_ _|__| | | ___ 
#      | |/ _` | |/ _ \
#      | | (_| | |  __/
#     |___\__,_|_|\___|
#                      
windowrule = idle_inhibit fullscreen, match:class .*

#      ____  _      _                       ___             ____  _      _                  
#     |  _ \(_) ___| |_ _   _ _ __ ___     |_ _|_ __       |  _ \(_) ___| |_ _   _ _ __ ___ 
#     | |_) | |/ __| __| | | | '__/ _ \_____| || '_ \ _____| |_) | |/ __| __| | | | '__/ _ \
#     |  __/| | (__| |_| |_| | | |  __/_____| || | | |_____|  __/| | (__| |_| |_| | | |  __/
#     |_|   |_|\___|\__|\__,_|_|  \___|    |___|_| |_|     |_|   |_|\___|\__|\__,_|_|  \___|
#                                                                                           
windowrule {
    name = hyde_picture_in_picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    tag = +picture-in-picture
    tag = +hyde_picture_in_picture
    float = true
    keep_aspect_ratio = true
    move = (monitor_w*0.73) (monitor_h*0.72)
    size = (monitor_w*0.25) (monitor_h*0.25)
    pin = true
}

#      _____ _             _   _             
#     |  ___| | ___   __ _| |_(_)_ __   __ _ 
#     | |_  | |/ _ \ / _` | __| | '_ \ / _` |
#     |  _| | | (_) | (_| | |_| | | | | (_| |
#     |_|   |_|\___/ \__,_|\__|_|_| |_|\__, |
#                                      |___/ 

windowrule = float true, match:class .*

# Max and min sizing for floating windows
windowrule = min_size 1280 720, match:class .*
windowrule = max_size 1920 1080, match:class .*

# Opacity rules: [active] [inactive] [fullscreen]
windowrule = opacity 1.0 $& 1.0 $& 1,match:class .*
windowrule = opacity 0.8 $& 0.8 $& 1,match:class ^(kitty)$
windowrule = opacity 0.80 $& 0.80 $& 1,match:class ^(org.kde.*)$

#overides
windowrule = min_size 360 480, match:class ^(org.kde.kcalc)$
windowrule = max_size 360 480, match:class ^(org.kde.kcalc)$

# workaround for jetbrains IDEs dropdowns/popups cause flickering
windowrule = no_initial_focus true,match:class ^(.*jetbrains.*)$,match:title ^(win[0-9]+)$

#         _          _                 _   _             
#        / \   _ __ (_)_ __ ___   __ _| |_(_) ___  _ __  
#       / _ \ | '_ \| | '_ ` _ \ / _` | __| |/ _ \| '_ \ 
#      / ___ \| | | | | | | | | | (_| | |_| | (_) | | | |
#     /_/   \_\_| |_|_|_| |_| |_|\__,_|\__|_|\___/|_| |_|
                                          
windowrule {
  name = pop-in
  match:class = .*
  animation = popin
}

# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = blur true,match:namespace rofi
layerrule = ignore_alpha 0,match:namespace rofi
layerrule = blur true,match:namespace notifications
layerrule = ignore_alpha 0,match:namespace notifications
layerrule = blur true,match:namespace swaync-notification-window
layerrule = ignore_alpha 0,match:namespace swaync-notification-window
layerrule = blur true,match:namespace swaync-control-center
layerrule = ignore_alpha 0,match:namespace swaync-control-center
layerrule = blur true,match:namespace logout_dialog

# hyprlang endif
